### ISSUE TITLE
loading heat state causes temperatures not to change over time

### ISSUE THREAD

**Issue by rmm-fcul** [plsm/assisi-playground#3]
with reference to branch `heat-state` 

The heat conductance seems to be disabled if the heat.state is loaded externally.  The test case I used has a region set to 44 instead of 23 (see input.png [1] and heat-state.txt [2]).  This does not change even after
leaving for a long period (see output.png)
![output](https://cloud.githubusercontent.com/assets/7782039/12951684/6f1e7508-d00b-11e5-877a-dba68226f404.png)

* bottom graph got wrong label -- it should say "temp dC, all". The cells that are not the top sensor remain at 44 for the entire period.

If we do not set the state, the temperatures do change (I didn't verify against the previous simulator).
![out2](https://cloud.githubusercontent.com/assets/7782039/12951678/6a68cdf6-d00b-11e5-94af-8831c3a00940.png)

[1]: initial condition (image)
![input](https://cloud.githubusercontent.com/assets/7782039/12951695/7b16ed22-d00b-11e5-9b3d-89ad97aedcdc.png)

[2]: initial condition (config)
[heat-state.txt](https://github.com/plsm/assisi-playground/files/124997/heat-state.txt)

[3]: test code 
[test_heat_state.py.txt](https://github.com/plsm/assisi-playground/files/124994/test_heat_state.py.txt)

**Comment by plsm** [comment]
Solved by commit 4f41b9b5617a53f60802fa16bd274c733c3d6019
